feat: use treesitter_module
JoosepAlviste/nvim-ts-context-commentstring pull request #2
Opened 2021-03-18 11:39 UTC by elianiva

close #1

2021-03-18 16:33 UTC, JoosepAlviste requested changes

2021-03-18 16:33 UTC, JoosepAlviste commented on lua/ts_context_commentstring/internal.lua
> +function M.attach()
If I understand it correctly, then it looks like `attach` is called for every buffer that treesitter attaches to. I think that the `setup` function is no longer necessary and can be deleted. We could call `setup_filetype` instead (it would make sense to name `setup_filetype` to `setup_buffer` though).

What do you think?

2021-03-18 16:33 UTC, JoosepAlviste commented on lua/ts_context_commentstring/internal.lua
> +  M.config = vim.tbl_deep_extend(
(Continuing from the other comment)

If `setup` is deleted, then we would need to update the default config somehow. Do you know if there's a good way to set default values for a treesitter module?

If there isn't then we could merge the configs in `attach`. Something like this:

```lua
function M.attach()
  M.config = vim.tbl_deep_extend(
    'force',
    M.config,
    configs.get_module('context_commentstring').config or {}
  )
  
  return M.setup_filetype()
end
```

Do you have any thoughts on this?

2021-03-18 22:14 UTC, elianiva commented on lua/ts_context_commentstring/internal.lua
> +  M.config = vim.tbl_deep_extend(
yes, I think moving `setup` to `attach` would be better since nobody is ever going to use `setup` after we move them to nvim-treesitter module

2021-03-19 03:17 UTC, elianiva commented
I think I've addressed the issue, let me know what you think :)

2021-03-19 07:43 UTC, merged

2021-03-19 07:44 UTC, JoosepAlviste commented
Looks great! Thanks for the contribution!