Add twig commentstring
JoosepAlviste/nvim-ts-context-commentstring pull request #48
Opened 2022-10-12 19:43 UTC by gbprod

Add commentstring for [twig](twig.symfony.com) templating language :)

2022-10-13 17:46 UTC, JoosepAlviste requested changes
Hey, thanks for the PR! I'd change one small thing though

2022-10-14 06:54 UTC, gbprod commented on lua/ts_context_commentstring/internal.lua
> +  twig = "{#%s#}",
Resolved !

2022-10-14 08:29 UTC, gbprod commented
I think that Stylua Action is broken, I send a fix

2022-10-14 08:33 UTC, JoosepAlviste approved these changes

2022-10-14 08:34 UTC, merged

2022-10-14 08:34 UTC, JoosepAlviste commented
Oh seems so, thanks for the contribution!