Language additions and sorting filetypes
JoosepAlviste/nvim-ts-context-commentstring pull request #78
Opened 2023-10-06 14:58 UTC by felixnorden

Wanted to add in some additional language comment types in here as I was lacking some of them myself in my flow using LazyVim! Please let me know if there's anything needed further to get this merged in!

This commit will:
- Add in comment support for:
  - `sh` files
  - `zsh` files
  - `solidity` files
  - `c` files
- Sort all languages in alphabetical order based on filetype/name
- Rename the `config` table inside the `config` to `languages` as written in the TODO above

2023-10-06 20:07 UTC, JoosepAlviste requested changes
Hey, thanks for the PR! I had some thoughts about the `config` key renaming, so that it wouldn't be a breaking change.

2023-10-06 20:07 UTC, JoosepAlviste commented on lua/ts_context_commentstring/config.lua
> +  return M.config.languages
One issue with this is that it is a breaking change, users will need to change their configuration after updating the plugin. I think that we could keep `languages`, but also read the `config` key and merge the results, so that both would be used. Eventually, we can deprecate the `config` option and remove it after that.

Also, we should probably update the docs in `docs/nvim-ts-context-commentstring.txt` with the new config option so that users would start using the preferred config name.

2023-10-06 21:26 UTC, felixnorden commented
Sounds like a good plan, I’ll look to get those pieces covered tomorrow with a new commit to make sure we have a non-breaking change and update docs! On Oct 6, 2023, at 21:07, Joosep Alviste ***@***.***> wrote:﻿
@JoosepAlviste requested changes on this pull request.

Hey, thanks for the PR! I had some thoughts about the config key renaming, so that it wouldn't be a breaking change.

In lua/ts_context_commentstring/config.lua:
> -  return M.config.config
+  return M.config.languages

One issue with this is that it is a breaking change, users will need to change their configuration after updating the plugin. I think that we could keep languages, but also read the config key and merge the results, so that both would be used. Eventually, we can deprecate the config option and remove it after that.
Also, we should probably update the docs in docs/nvim-ts-context-commentstring.txt with the new config option so that users would start using the preferred config name.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-10-08 21:25 UTC, felixnorden commented
@JoosepAlviste , I added in the changes but wasn't sure about how to mark the `config` field for deprecation properly. Apart from this, I think that the logic should be in order for merging `languages` and `config` based on the internal logic and allowing for overrides/extensions.

Let me know if you want me to put the merge from `keep` to `force` in the table merge, however, in case this needs to be done for end-user overrides/extensions to have priority over the supported languages out of the box!

2023-10-09 17:19 UTC, JoosepAlviste requested changes
Thanks for making the changes! I had a couple more thoughts on how to make this change less breaking for users 😅

2023-10-09 17:19 UTC, JoosepAlviste commented on lua/ts_context_commentstring/config.lua
> +  return vim.tbl_extend('keep', M.config.languages, M.config.config)
Like you mentioned, I would use `force` rather than `keep` as otherwise, if I have configured this plugin with the old `config` key like so:

```lua
context_commentstring = {
  enable = true,
  enable_autocmd = false,
  config = {
    tsx = {
      __default = '// -- %s',
    },
  },
},
```

then it would not use my configured value, but would overwrite them with the defaults from `M.config.languages`. I'd prefer to keep the old configuration working for users (for now).

2023-10-09 17:19 UTC, JoosepAlviste commented on lua/ts_context_commentstring/config.lua
> +  return vim.tbl_extend('keep', M.config.languages, M.config.config)
One problem that we have with this approach is that if I have configured the plugin like so:

```lua
context_commentstring = {
  enable = true,
  languages = {
    tsx = {
      __default = '// -- %s',
    },
  },
},
```

then it would overwrite the `tsx` configuration entirely:

```lua
tsx = {
  __default = "// -- %s",
},
```

rather than keeping the defaults for the rest of the fields.

I think that we could use `vim.tbl_deep_extend` so that the configurations would be recursively merged, only overwriting the `__default` key. I think that that's how it worked before these changes, so I would keep the same behavior.

2023-10-09 17:19 UTC, JoosepAlviste commented on lua/ts_context_commentstring/config.lua
> +  ---@deprecated
I think that the `@deprecated` annotation only works for functions: https://luals.github.io/wiki/annotations/#deprecated 😞 

But I think that we could keep it here. I would also add some note, though, to use `languages` instead (e.g., `---@deprecated Use the languages configuration instead`).

2023-10-09 23:00 UTC, felixnorden commented
Roger that, will have a look on your comments and make sure we cover that as well! 👍 thanks for taking the time to go through it!

2023-10-11 17:25 UTC, felixnorden commented on lua/ts_context_commentstring/config.lua
> +  return vim.tbl_extend('keep', M.config.languages, M.config.config)
Updated this now, so feel free to verify that it's correct. Doing a forced deep merge to ensure that we are backwards compatible with user overrides 👍

2023-10-11 17:25 UTC, felixnorden commented on doc/nvim-ts-context-commentstring.txt
Updated all occurrences of `config` in relation to the `languages` references and added in a small parentheses with the mention that `config` is deprecated as well!

2023-10-12 15:33 UTC, JoosepAlviste approved these changes

2023-10-12 15:35 UTC, merged

2023-10-12 15:36 UTC, JoosepAlviste commented
Looks great now, thanks for the contribution! And thanks for taking care of the config key renaming 😄