Remove nvim-treesitter, use nvim 0.9+ core utilities
JoosepAlviste/nvim-ts-context-commentstring pull request #80
Opened 2023-11-02 23:48 UTC by Slotos

With 0.9 being the minimal version for this plugin, nvim-treesitter is quite literally a fifth wheel for its functionality. It installs and updates parsers, but everything this plugin needs to operate afterwards is available in the core `vim.treesitter` utilities set.

I also borrowed a test setup from aerial.nvim, to create a minimal setup launcher bash script that truly isolates minimal config from main user configuration.

2023-11-11 22:11 UTC, JoosepAlviste requested changes
Thanks for the great PR! It's nice to see that all the necessary parts are actually available in Neovim core now. We can get rid of quite a lot of unnecessary code 😄

I found one issue and had a couple other thoughts on how to improve this a bit.

2023-11-11 22:11 UTC, JoosepAlviste commented on lua/ts_context_commentstring/utils.lua
> +  end, language_tree:children())[1]
This breaks if there are no relevant children in the tree. It looks like previously, the language tree itself would also be included in `:trees()`, but `:children()` only returns the actual children. So, if we have a `tsx` tree with no children, the children and `ltree` would be empty, and this function would return early.

To reproduce, have a `.tsx` file with the following contents and try to comment the `<h1>` line:

```tsx
(
  <div>
    <h1>Hello</h1>
  </div>
)
```

It will comment with `// %s`, but it should be `{/* %s */}`.

One way to fix it would be to default this to `language_tree`:

```suggestion
  end, language_tree:children())[1] or language_tree
```

2023-11-12 19:56 UTC, Slotos commented on lua/ts_context_commentstring/internal.lua
> -  config.update(require('nvim-treesitter.configs').get_module 'context_commentstring')
That's a good point. I got overeager, as I use default configuration. I'll add a deprecation pathway.

2023-11-12 22:34 UTC, Slotos commented on lua/ts_context_commentstring/utils.lua
> +  end, language_tree:children())[1]
Oh, this is really a great example. There's a bug on `main` when you try to comment and uncomment `<div>`. Similarly, the same bug appears if you try to comment and uncomment all three lines containing `<div>`.

This boils down to `{/* */}` being not a comment, but an object wrapping a comment.

I believe I came up with a working, if hacky, solution by adding `object = '{/* %s */}',` config to TSX defaults.

2023-11-12 23:37 UTC, Slotos commented on README.md
> -- [`nvim-treesitter`](https://github.com/nvim-treesitter/nvim-treesitter)
I've added a mention of parsers being required, with a link to nvim-treesitter.

2023-11-12 23:53 UTC, Slotos commented on lua/ts_context_commentstring/internal.lua
> -  config.update(require('nvim-treesitter.configs').get_module 'context_commentstring')
Updated.

Backwards compatibility routine adds some extra requires that can slow down loading for people using `nvim-treesitter`'s main branch. I added a global variable check to disable this routine, and mentioned it in a readme.

2023-11-12 23:54 UTC, Slotos commented on utils/run_minimal.sh
> +#!/usr/bin/env bash
I updated the script to always create test env near itself, and updated github issue template.

2023-11-15 18:52 UTC, JoosepAlviste commented on lua/ts_context_commentstring/utils.lua
> +  end, language_tree:children())[1]
I think that you mean this issue: https://github.com/JoosepAlviste/nvim-ts-context-commentstring/issues/29 which is a bit more difficult to solve. With the current fix, this breaks, for example:

```ts
const a = {
    |hello: 'world',
    ^ cursor, commenting
}
```

now results in

```ts
const a = {
    {/* hello: 'world', */}
}
```

I don't think we should tackle that issue in this PR.

I just meant this case:

```tsx
(
  <div>
    |<h1>Hello</h1>
    ^ cursor, commenting
  </div>
)
```

results in

```tsx
(
  <div>
    // <h1>Hello</h1>
  </div>
)
```

which should be solved by the original suggestion I made (to add `or language_tree`)

2023-11-15 21:25 UTC, Slotos commented on lua/ts_context_commentstring/utils.lua
> +  end, language_tree:children())[1]
Oof, you're right, best not to tackle this here. Especially with me not working with TSX files currently.

I removed the "fix".

2023-11-18 18:55 UTC, JoosepAlviste commented on lua/ts_context_commentstring/internal.lua
> +  vim.deprecate("context_commentstring module", "use require('ts_context_commentstring').setup {} and set vim.g.skip_ts_context_commentstring_module = true to speed up loading", "in the future", "ts_
This is how the deprecation message looks like right now:

```
   Warn  20:49:15 notify.warn context_commentstring module is deprecated, use use require('ts_context_commentstring').setup {} and set vim.g.skip_ts_context_commentstring_module = true to speed up loading instead.
This feature will be removed in ts_context_commentstring version in the future
```

I'd make two small changes here:

```suggestion
  vim.deprecate("context_commentstring Treesitter module", "require('ts_context_commentstring').setup {} and set vim.g.skip_ts_context_commentstring_module = true to speed up loading", "in the future", "ts_context_commentstring")
```

just to make the text look a bit better. Resulting in:

```
   Warn  20:52:29 notify.warn context_commentstring Treesitter module is deprecated, use require('ts_context_commentstring').setup {} and set vim.g.skip_ts_context_commentstring_module = true to speed up loading instead.
This feature will be removed in ts_context_commentstring version in the future
```

What do you think?

2023-11-18 18:56 UTC, JoosepAlviste commented
This looks great now! Just the Stylua check to fix and the deprecation message wording, and then we can merge it 🎉

Thanks for taking care of the fixes and improvements!

2023-11-18 20:42 UTC, Slotos commented on lua/ts_context_commentstring/internal.lua
> +  vim.deprecate("context_commentstring module", "use require('ts_context_commentstring').setup {} and set vim.g.skip_ts_context_commentstring_module = true to speed up loading", "in the future", "ts_
I'll specify "nvim-treesitter", as "Treesitter" could potentially be mistaken for the parser framework itself.

2023-11-18 21:58 UTC, JoosepAlviste approved these changes

2023-11-18 21:58 UTC, merged

2023-11-18 22:01 UTC, JoosepAlviste commented
Thanks for the great work on this! It feels great to get rid of some useless code 🎉 

I also created an issue with the breaking changes and mentioned this there: https://github.com/JoosepAlviste/nvim-ts-context-commentstring/issues/82#issuecomment-1817659634 and updated the integrations wiki: https://github.com/JoosepAlviste/nvim-ts-context-commentstring/wiki/Integrations.

Hopefully this won't be too big of a big pain for users 🤞